variables:
  namespace: "it-ent-int"

include:
  - project: 'bismarck-shared/ci-cd/standard-ci'
    ref: kustomize
    file: '1-base-ci-template.yml'
  - project: 'bismarck-shared/ci-cd/standard-ci'
    ref: kustomize
    file: '2-docker-ci-template.yml'
  - project: 'bismarck-shared/ci-cd/standard-ci'
    ref: kustomize
    file: '3-deploy-test-ci-template.yml'
  - project: 'bismarck-shared/ci-cd/standard-ci'
    ref: kustomize
    file: '4-start-workflow-template.yml'
  - project: 'bismarck-shared/ci-cd/standard-ci'
    ref: kustomize
    file: '5-deploy-staging-ci-template.yml'
  - project: 'bismarck-shared/ci-cd/standard-ci'
    ref: kustomize
    file: '6-canary-ci-template.yml'
  - project: 'bismarck-shared/ci-cd/standard-ci'
    ref: kustomize
    file: '7-rollout-prod-ci-template.yml'
  - project: 'bismarck-shared/ci-cd/standard-ci'
    ref: kustomize
    file: '8-rollback-prod-ci-template.yml'

build:
  tags:
    - docker-itsd
  stage: build
  image: golang:1.17-alpine
  artifacts:
    paths:
      - app
    expire_in: 1 hours
  script: 
    - go build .
