apiVersion: v1
kind: ConfigMap
metadata:
  name: prepaidcataloguebatch-config
  namespace: intbatchjob
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-prepaidcataloguebatch
  namespace: intbatchjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-prepaidcataloguebatch
      env: uat
      version: 1.0.0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%   
  template:
    metadata:
      labels:
        app: deploy-prepaidcataloguebatch
        env: uat
        version: 1.0.0
    spec:
      containers:
      - name: containers-prepaidcataloguebatch
        image: ${image}
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 50m
            memory: 256Mi
            ephemeral-storage: 32Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: prepaidcataloguebatch-config
        volumeMounts:
          - name: prepaidcataloguebatch-config
            mountPath: /app/configmap/
            readOnly: true
      volumes:
        - name: prepaidcataloguebatch-config
          configMap:
            name: prepaidcataloguebatch-config
      imagePullSecrets:
      - name: intregcred